let citation = [
    "La façon de commencer est d'arrêter de parler et de commencer à faire. -Walt Disney",
    "Votre temps est limité, alors ne le gaspillez pas en vivant les échecs de la vie de quelqu'un d'autre. Ne vous laissez pas piéger par le dogme - qui consiste à vivre avec les résultats de la pensée des autres. -Steve Jobs",
    "Si la vie était prévisible, elle cesserait d'être la vie, et serait sans saveur. -Eleanor Roosevelt",
    "Si vous regardez ce que vous avez dans la vie, vous aurez toujours plus. Si vous regardez ce que vous n'avez pas dans la vie, vous n'en aurez jamais assez. -Oprah Winfrey",
    "Si vous fixez vos objectifs à un niveau ridiculement élevé et que vous échouez, vous échouerez par-dessus le succès de tous les autres. -James Cameron",
    "La vie, c'est ce qui arrive quand on est occupé à faire d'autres projets. -John Lennon",
    "Répandez l'amour partout où vous allez. Que personne ne vienne jamais à vous sans en sortir plus heureux. -Mère Teresa",
    "Lorsque vous arrivez au bout de votre corde, faites un nœud et accrochez-vous. -Franklin D. Roosevelt",
    "N'oubliez jamais que vous êtes absolument unique. Comme tout le monde. -Margaret Mead",
    "Ne jugez pas chaque jour par la récolte que vous faites, mais par les graines que vous plantez. -Robert Louis Stevenson",
    "L'avenir appartient à ceux qui croient en la beauté de leurs rêves. -Eleanor Roosevelt",
    "Répands l'amour partout où tu vas. Que personne ne vienne à vous sans en repartir plus heureux. -MèreTeresa",
    "Quand vous arrivez au bout de votre corde, faites un nœud et accrochez-vous. -FranklinD. Roosevelt",
    "N'oubliez jamais que vous êtes absolument unique. Comme tout le monde. -MargaretMead",
    "Ne jugez pas chaque jour par la récolte que vous faites, mais par les graines que vous plantez. -RobertLouis Stevenson",
    "L'avenir appartient à ceux qui croient en la beauté de leurs rêves. -EleanorRoosevelt",
    "Dis-moi et j'oublie. Enseignez-moi et je me souviens. Faites-moi participer et j'apprends.-Benjamin Franklin",
    "Les meilleures et les plus belles choses du monde ne peuvent être vues ni même touchées - elles doivent être ressenties avec le cœur. -HelenKeller",
    "C'est dans nos moments les plus sombres que nous devons nous concentrer pour voir la lumière. -Aristote",
    "Celui qui est heureux rendra les autres heureux aussi. -AnneFrank",
    "Ne va pas là où le chemin peut mener, va plutôt là où il n'y a pas de chemin et laisse une trace. -RalphWaldo Emerson",
    "Vous rencontrerez de nombreuses défaites dans la vie, mais ne vous laissez jamais abattre. -Maya Angelou",
    "La plus grande gloire de la vie ne réside pas dans la chute, mais dans le fait de se relever chaque fois que l'on tombe. -Nelson Mandela",
    "Au final, ce ne sont pas les années de votre vie qui comptent. C'est la vie dans vos années. -Abraham Lincoln",
    "Ne laissez jamais la peur de faire un faux pas vous empêcher de jouer le jeu. -Babe Ruth",
    "La vie est soit une aventure audacieuse, soit rien du tout. -Helen Keller",
    "La plupart des échecs de la vie sont des personnes qui n'ont pas réalisé à quel point elles étaient proches du succès lorsqu'elles ont abandonné. -Thomas A. Edison",
    "Vous avez un cerveau dans votre tête. Vous avez des pieds dans vos chaussures. Tu peux te diriger dans la direction que tu veux. -Dr. Seuss",
    "Si la vie était prévisible, elle cesserait d'être la vie et serait sans saveur. -EleanorRoosevelt",
    "La vie est une succession de leçons qui doivent être vécues pour être comprises. -RalphWaldo Emerson",
    "Vous ferez face à de nombreuses défaites dans la vie, mais ne vous laissez jamais vaincre. -MayaAngelou",
    "Ne laissez jamais la peur de perdre vous empêcher de jouer le jeu. -Babe Ruth",
    "La vie n'est jamais juste, et c'est peut-être une bonne chose pour la plupart d'entre nous qu'elle ne le soit pas. -OscarWilde ",
    "Le seul voyage impossible est celui que vous ne commencez jamais. -TonyRobbins",
    "Dans cette vie, nous ne pouvons pas faire de grandes choses. Nous pouvons seulement faire de petites choses avec un grand amour. -MèreTeresa",
    "Seule une vie vécue pour les autres est une vie qui en vaut la peine. -Albert Einstein",
    "Le but de notre vie est d'être heureux. -DalaiLama",
    "La plus grande gloire de la vie ne consiste pas à ne jamais tomber, mais à se relever chaque fois que l'on tombe. -Nelson Mandela",
    "La façon de commencer est d'arrêter de parler et de commencer à faire. -Walt Disney",
    "Votre temps est limité, alors ne le gaspillez pas en vivant la vie de quelqu'un d'autre. Ne vous laissez pas piéger par le dogme - qui consiste à vivre avec les résultats de la pensée des autres. -Steve Jobs",
    "Si vous regardez ce que vous avez dans la vie, vous aurez toujours plus. Si vous regardez ce que vous n'avez pas dans la vie, vous n'en aurez jamais assez. -Oprah Winfrey",
    "Si vous fixez vos objectifs à un niveau ridiculement élevé et que vous échouez, vous échouerez par-dessus le succès de tous les autres. -James Cameron",
    "La vie, c'est ce qui arrive quand on est occupé à faire d'autres projets. -John Lennon",
    "Répandez l'amour partout où vous allez. Que personne ne vienne jamais à vous sans en sortir plus heureux. -Mère Teresa",
    "N'oubliez jamais que vous êtes absolument unique. Comme tout le monde. -Margaret Mead",
    "Ne jugez pas chaque jour par la récolte que vous faites, mais par les graines que vous plantez. -Robert Louis Stevenson",
    "Les meilleures et les plus belles choses du monde ne peuvent être vues ni même touchées - elles doivent être ressenties avec le cœur. -Helen Keller",
    "C'est dans nos moments les plus sombres que nous devons nous concentrer pour voir la lumière. -Aristote",
    "Celui qui est heureux rendra les autres heureux aussi. -Anne Frank",
    "Ne va pas là où le chemin peut mener, va plutôt là où il n'y a pas de chemin et laisse une trace. -Ralph Waldo Emerson",
    "Gardez le sourire, car la vie est une chose magnifique et il y a tant de raisons de sourire. -Marilyn Monroe",
    "La vie est une longue leçon d'humilité. -James M. Barrie",
    "En trois mots, je peux résumer tout ce que j'ai appris sur la vie : elle continue. -Robert Frost",
    "Aimez la vie que vous vivez. Vivez la vie que vous aimez. -Bob Marley",
    "La vie est soit une aventure audacieuse, soit rien du tout. -Helen Keller",
    "Vous avez un cerveau dans votre tête. Vous avez des pieds dans vos chaussures. Tu peux te diriger dans la direction que tu veux. -Dr. Seuss",
    "La vie est faite de tant de séparations soudées ensemble. -Charles Dickens",
    "La vie, c'est essayer des choses pour voir si elles fonctionnent. -Ray Bradbury",
    "La plupart des échecs de la vie sont des personnes qui n'ont pas réalisé à quel point elles étaient proches du succès lorsqu'elles ont abandonné. -Thomas A. Edison",
    "Gardez le sourire, parce que la vie est une chose magnifique et qu'il y a tellement de raisons de sourire. -MarilynMonroe",
    "La vie est une longue leçon d'humilité. -James M. Barrie",
    "Aimez la vie que vous vivez. Vis la vie que tu aimes. -Bob Marley",
    "La vie est soit une aventure audacieuse, soit rien du tout. -HelenKeller",
    "Vous avez un cerveau dans votre tête. Vous avez des pieds dans vos chaussures. Tu peux te diriger dans la direction que tu veux. -Dr.Seuss",
    "La vie est faite de tant de séparations soudées ensemble. -CharlesDickens",
    "Votre temps est limité, alors ne le gaspillez pas en vivant la vie de quelqu'un d'autre. Ne vous laissez pas piéger par le dogme - qui consiste à vivre avec les résultats de la pensée des autres. -SteveJobs",
    "La vie, c'est essayer des choses pour voir si elles fonctionnent. -RayBradbury",
    "Beaucoup des échecs de la vie sont des personnes qui n'ont pas réalisé à quel point elles étaient proches du succès lorsqu'elles ont abandonné. -ThomasA. Edison",
    "Le succès n'est pas définitif ; l'échec n'est pas fatal : c'est le courage de continuer qui compte. -Winston S. Churchill",
    "Le succès vient généralement à ceux qui sont trop occupés pour le chercher. -Henry David Thoreau",
    "La façon de commencer est d'arrêter de parler et de commencer à faire. -Walt Disney",
    "Si vous regardez vraiment de près, la plupart des succès du jour au lendemain ont pris beaucoup de temps. -Steve Jobs",
    "Le secret de la réussite consiste à faire les choses courantes de manière inhabituelle. -John D. Rockefeller Jr.",
    "Je constate que plus je travaille dur, plus j'ai de la chance. -Thomas Jefferson",
    "Le véritable test n'est pas de savoir si vous évitez cet échec, car vous ne le ferez pas. Il s'agit de savoir si vous le laissez s'endurcir ou vous faire honte en restant inactif, ou si vous en tirez des leçons, si vous choisissez de persévérer. -Barack Obama",
    "Le secret de la réussite consiste à faire les choses courantes de manière inhabituelle. -JohnD. Rockefeller Jr.",
    "Je trouve que plus je travaille dur, plus je semble avoir de la chance. -ThomasJefferson",
    "Le succès n'est pas définitif ; l'échec n'est pas fatal : c'est le courage de continuer qui compte. -WinstonS. Churchill",
    "Ne vous laissez pas distraire par les critiques. Rappelez-vous - le seul goût du succès que certaines personnes obtiennent est de faire une bouchée de vous. -ZigZiglar",
    "Le succès vient généralement à ceux qui sont trop occupés pour le chercher. -HenryDavid Thoreau",
    "Je n'ai jamais rêvé du succès, j'ai travaillé pour l'obtenir. -EsteeLauder",
    "Le succès semble être lié à l'action. Les personnes qui réussissent continuent d'avancer. Ils font des erreurs, mais ils n'abandonnent pas.-Conrad Hilton",
    "Il n'y a pas de secrets pour le succès. C'est le résultat de la préparation, du travail acharné et de l'apprentissage de l'échec.  -Colin Powell",
    "Le véritable test n'est pas de savoir si vous évitez cet échec, car vous ne le ferez pas. Il s'agit de savoir si vous le laissez se durcir ou vous faire honte pour vous pousser à l'inaction, ou si vous en tirez des leçons ; si vous choisissez de persévérer. -Barack Obama",
    "Le véritable test n'est pas de savoir si vous évitez cet échec, car vous ne le ferez pas. Il s'agit de savoir si vous le laissez se durcir ou vous faire honte pour vous pousser à l'inaction, ou si vous en tirez des leçons ; si vous choisissez de persévérer. -Barack Obama",
    "Il vaut mieux échouer dans l'originalité que de réussir dans l'imitation. -HermanMelville",
    "Les gens qui réussissent font ce que les gens qui ne réussissent pas ne veulent pas faire. Ne souhaitez pas que ce soit plus facile ; souhaitez que vous soyez meilleur. -JimRohn",
    "La route du succès et la route de l'échec sont presque exactement les mêmes.-Colin R. Davis",
    "J'ai échoué sur le chemin du succès. -ThomasEdison",
    "Si vous fixez vos objectifs à un niveau ridiculement élevé et que c'est un échec, vous échouerez au-dessus du succès de tous les autres. -JamesCameron",
    "Si vous y regardez de plus près, la plupart des réussites du jour au lendemain ont pris beaucoup de temps. -Steve Jobs",
    "Un homme qui réussit est celui qui peut poser des fondations solides avec les briques que les autres ont jetées sur lui. -DavidBrinkley",
    "Les choses marchent mieux pour ceux qui font le meilleur de la façon dont les choses marchent. -JohnWooden",
    "Essayez de ne pas devenir un homme de succès. Devenez plutôt un homme de valeur. -AlbertEinstein",
    "N'ayez pas peur d'abandonner le bon pour aller vers le grand. -JohnD. Rockefeller",
    "Gardez toujours à l'esprit que votre propre résolution à réussir est plus importante que toute autre chose. -AbrahamLincoln",
    "Le succès consiste à marcher d'échec en échec sans perdre son enthousiasme. -WinstonChurchill",
    "Vous savez que vous êtes sur la voie du succès si vous êtes prêt à faire votre travail sans être payé pour cela. -OprahWinfrey",
    "Si vous voulez atteindre l'excellence, vous pouvez y arriver aujourd'hui. Dès cette seconde, cessez de faire un travail moins qu'excellent.  -ThomasJ. Watson",
    "Si vous voulez sincèrement quelque chose, ne l'attendez pas - apprenez à être impatient. -GurbakshChahal",
    "Le seul endroit où le succès passe avant le travail, c'est dans le dictionnaire. -VidalSassoon",
    "Si vous n'êtes pas prêt à risquer l'habituel, vous devrez vous contenter de l'ordinaire. -JimRohn",
    "Avant toute chose, la préparation est la clé du succès. -AlexanderGraham Bell",
    "Les gens qui réussissent ont un élan. Plus ils réussissent, plus ils veulent réussir et plus ils trouvent un moyen de réussir. De même, lorsque quelqu'un échoue, la tendance est de s'engager dans une spirale descendante qui peut même devenir une prophétie auto-réalisatrice. -TonyRobbins",
    "Vous ratez 100% des tirs que vous ne prenez pas. -Wayne Gretzky",
    "Que tu penses que tu peux ou que tu penses que tu ne peux pas, tu as raison. -Henry Ford",
    "J'ai appris au fil des ans que lorsque l'on a une idée bien arrêtée, la peur diminue. -Rosa Parks",
    "Je ne peux pas changer le monde à moi seul, mais je peux jeter une pierre sur l'eau pour créer de nombreuses ondulations. -Mère Teresa",
    "Rien n'est impossible, le mot lui-même dit : \"Je suis possible\". -Audrey Hepburn",
    "La question n'est pas de savoir qui va me laisser faire, mais qui va m'en empêcher. -Ayn Rand",
    "La seule personne que vous êtes destiné à devenir est celle que vous décidez d'être. -Ralph Waldo Emerson",
    "Croyez que vous pouvez et vous êtes à mi-chemin. -ThéodoreRoosevelt",
    "La seule personne que vous êtes destiné à devenir est la personne que vous décidez d'être. -RalphWaldo Emerson",
    "J'ai appris que les gens oublieront ce que vous avez dit, les gens oublieront ce que vous avez fait, mais les gens n'oublieront jamais ce que vous leur avez fait ressentir. -MayaAngelou",
    "La question n'est pas de savoir qui va me laisser faire ; c'est de savoir qui va m'arrêter. -AynRand",
    "Gagner n'est pas tout, mais vouloir gagner l'est. -VinceLombardi",
    "Que tu penses que tu peux ou que tu penses que tu ne peux pas, tu as raison. -HenryFord",
    "Vous devenez ce que vous croyez. -OprahWinfrey",
    "La chose la plus difficile est la décision d'agir, le reste n'est que ténacité. -AmeliaEarhart",
    "Comme c'est merveilleux que personne n'ait à attendre un seul instant avant de commencer à améliorer le monde. -AnneFrank",
    "Une vie non examinée ne vaut pas la peine d'être vécue. -Socrates",
    "Tout ce que vous avez toujours voulu se trouve de l'autre côté de la peur. -GeorgeAddair",
    "Rêvez grand et osez échouer. -NormanVaughan",
    "Vous pouvez être déçu si vous échouez, mais vous êtes condamné si vous n'essayez pas.-Beverly Sills",
    "La vie, c'est 10% de ce qui m'arrive et 90% de la façon dont j'y réagis. -CharlesSwindoll",
    "Peu importe la vitesse à laquelle vous avancez, tant que vous ne vous arrêtez pas.-Confucius",
    "Quand tout semble aller contre vous, rappelez-vous que l'avion décolle contre le vent, pas avec. -HenryFord",
    "Trop d'entre nous ne vivent pas leurs rêves parce qu'ils vivent leurs peurs. -LesBrown",
    "J'ai appris au fil des ans que lorsque l'on a une idée bien arrêtée, cela diminue la peur. -RosaParks",
    "Je n'ai pas raté le test. J'ai juste trouvé 100 façons de le faire mal. -Benjamin Franklin",
    "Si on vous offre un siège sur une fusée, ne demandez pas quel siège ! Montez simplement dessus.  -SherylSandberg",
    "J'attribue mon succès à cela : Je n'ai jamais donné ou accepté d'excuse. -FlorenceNightingale",
    "e préfère mourir de passion que d'ennui. -Vincentvan Gogh",
    "Si tu regardes ce que tu as dans la vie, tu auras toujours plus. Si vous regardez ce que vous n'avez pas dans la vie, vous n'en aurez jamais assez. -OprahWinfrey",
    "Rêver, après tout, est une forme de planification. -GloriaSteinem",
    "Tout ce que l'esprit de l'homme peut concevoir et croire, il peut le réaliser. -NapoléonHill",
    "Premièrement, ayez un idéal pratique défini et clair ; un but, un objectif. Deuxièmement, ayez les moyens nécessaires pour atteindre vos fins ; la sagesse, l'argent, les matériaux et les méthodes. Troisièmement, adaptez tous vos moyens à cette fin. -Aristote",
    "La vie est un mystère qu'il faut vivre, et non un problème à résoudre. - Gandhi",
    "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte. - Winston Churchill",
    "Le bonheur n'est pas quelque chose de prêt à l'emploi. Il vient de vos propres actions. - Dalai Lama",
    "La plus grande gloire de la vie ne réside pas dans la chute, mais dans le fait de se relever chaque fois que l'on tombe. -Nelson Mandela",
    "Dans vingt ans, vous serez plus déçu par les choses que vous n'avez pas faites que par celles que vous avez faites. Alors, larguez les amarres, éloignez-vous du port sûr, attrapez les alizés dans vos voiles. Explorez, rêvez, découvrez. -MarkTwain",
];

let citationRestante = [
    "La façon de commencer est d'arrêter de parler et de commencer à faire. -Walt Disney",
    "Votre temps est limité, alors ne le gaspillez pas en vivant les échecs de la vie de quelqu'un d'autre. Ne vous laissez pas piéger par le dogme - qui consiste à vivre avec les résultats de la pensée des autres. -Steve Jobs",
    "Si la vie était prévisible, elle cesserait d'être la vie, et serait sans saveur. -Eleanor Roosevelt",
    "Si vous regardez ce que vous avez dans la vie, vous aurez toujours plus. Si vous regardez ce que vous n'avez pas dans la vie, vous n'en aurez jamais assez. -Oprah Winfrey",
    "Si vous fixez vos objectifs à un niveau ridiculement élevé et que vous échouez, vous échouerez par-dessus le succès de tous les autres. -James Cameron",
    "La vie, c'est ce qui arrive quand on est occupé à faire d'autres projets. -John Lennon",
    "Répandez l'amour partout où vous allez. Que personne ne vienne jamais à vous sans en sortir plus heureux. -Mère Teresa",
    "Lorsque vous arrivez au bout de votre corde, faites un nœud et accrochez-vous. -Franklin D. Roosevelt",
    "N'oubliez jamais que vous êtes absolument unique. Comme tout le monde. -Margaret Mead",
    "Ne jugez pas chaque jour par la récolte que vous faites, mais par les graines que vous plantez. -Robert Louis Stevenson",
    "L'avenir appartient à ceux qui croient en la beauté de leurs rêves. -Eleanor Roosevelt",
    "Répands l'amour partout où tu vas. Que personne ne vienne à vous sans en repartir plus heureux. -MèreTeresa",
    "Quand vous arrivez au bout de votre corde, faites un nœud et accrochez-vous. -FranklinD. Roosevelt",
    "N'oubliez jamais que vous êtes absolument unique. Comme tout le monde. -MargaretMead",
    "Ne jugez pas chaque jour par la récolte que vous faites, mais par les graines que vous plantez. -RobertLouis Stevenson",
    "L'avenir appartient à ceux qui croient en la beauté de leurs rêves. -EleanorRoosevelt",
    "Dis-moi et j'oublie. Enseignez-moi et je me souviens. Faites-moi participer et j'apprends.-Benjamin Franklin",
    "Les meilleures et les plus belles choses du monde ne peuvent être vues ni même touchées - elles doivent être ressenties avec le cœur. -HelenKeller",
    "C'est dans nos moments les plus sombres que nous devons nous concentrer pour voir la lumière. -Aristote",
    "Celui qui est heureux rendra les autres heureux aussi. -AnneFrank",
    "Ne va pas là où le chemin peut mener, va plutôt là où il n'y a pas de chemin et laisse une trace. -RalphWaldo Emerson",
    "Vous rencontrerez de nombreuses défaites dans la vie, mais ne vous laissez jamais abattre. -Maya Angelou",
    "La plus grande gloire de la vie ne réside pas dans la chute, mais dans le fait de se relever chaque fois que l'on tombe. -Nelson Mandela",
    "Au final, ce ne sont pas les années de votre vie qui comptent. C'est la vie dans vos années. -Abraham Lincoln",
    "Ne laissez jamais la peur de faire un faux pas vous empêcher de jouer le jeu. -Babe Ruth",
    "La vie est soit une aventure audacieuse, soit rien du tout. -Helen Keller",
    "La plupart des échecs de la vie sont des personnes qui n'ont pas réalisé à quel point elles étaient proches du succès lorsqu'elles ont abandonné. -Thomas A. Edison",
    "Vous avez un cerveau dans votre tête. Vous avez des pieds dans vos chaussures. Tu peux te diriger dans la direction que tu veux. -Dr. Seuss",
    "Si la vie était prévisible, elle cesserait d'être la vie et serait sans saveur. -EleanorRoosevelt",
    "La vie est une succession de leçons qui doivent être vécues pour être comprises. -RalphWaldo Emerson",
    "Vous ferez face à de nombreuses défaites dans la vie, mais ne vous laissez jamais vaincre. -MayaAngelou",
    "Ne laissez jamais la peur de perdre vous empêcher de jouer le jeu. -Babe Ruth",
    "La vie n'est jamais juste, et c'est peut-être une bonne chose pour la plupart d'entre nous qu'elle ne le soit pas. -OscarWilde ",
    "Le seul voyage impossible est celui que vous ne commencez jamais. -TonyRobbins",
    "Dans cette vie, nous ne pouvons pas faire de grandes choses. Nous pouvons seulement faire de petites choses avec un grand amour. -MèreTeresa",
    "Seule une vie vécue pour les autres est une vie qui en vaut la peine. -Albert Einstein",
    "Le but de notre vie est d'être heureux. -DalaiLama",
    "La plus grande gloire de la vie ne consiste pas à ne jamais tomber, mais à se relever chaque fois que l'on tombe. -Nelson Mandela",
    "La façon de commencer est d'arrêter de parler et de commencer à faire. -Walt Disney",
    "Votre temps est limité, alors ne le gaspillez pas en vivant la vie de quelqu'un d'autre. Ne vous laissez pas piéger par le dogme - qui consiste à vivre avec les résultats de la pensée des autres. -Steve Jobs",
    "Si vous regardez ce que vous avez dans la vie, vous aurez toujours plus. Si vous regardez ce que vous n'avez pas dans la vie, vous n'en aurez jamais assez. -Oprah Winfrey",
    "Si vous fixez vos objectifs à un niveau ridiculement élevé et que vous échouez, vous échouerez par-dessus le succès de tous les autres. -James Cameron",
    "La vie, c'est ce qui arrive quand on est occupé à faire d'autres projets. -John Lennon",
    "Répandez l'amour partout où vous allez. Que personne ne vienne jamais à vous sans en sortir plus heureux. -Mère Teresa",
    "N'oubliez jamais que vous êtes absolument unique. Comme tout le monde. -Margaret Mead",
    "Ne jugez pas chaque jour par la récolte que vous faites, mais par les graines que vous plantez. -Robert Louis Stevenson",
    "Les meilleures et les plus belles choses du monde ne peuvent être vues ni même touchées - elles doivent être ressenties avec le cœur. -Helen Keller",
    "C'est dans nos moments les plus sombres que nous devons nous concentrer pour voir la lumière. -Aristote",
    "Celui qui est heureux rendra les autres heureux aussi. -Anne Frank",
    "Ne va pas là où le chemin peut mener, va plutôt là où il n'y a pas de chemin et laisse une trace. -Ralph Waldo Emerson",
    "Gardez le sourire, car la vie est une chose magnifique et il y a tant de raisons de sourire. -Marilyn Monroe",
    "La vie est une longue leçon d'humilité. -James M. Barrie",
    "En trois mots, je peux résumer tout ce que j'ai appris sur la vie : elle continue. -Robert Frost",
    "Aimez la vie que vous vivez. Vivez la vie que vous aimez. -Bob Marley",
    "La vie est soit une aventure audacieuse, soit rien du tout. -Helen Keller",
    "Vous avez un cerveau dans votre tête. Vous avez des pieds dans vos chaussures. Tu peux te diriger dans la direction que tu veux. -Dr. Seuss",
    "La vie est faite de tant de séparations soudées ensemble. -Charles Dickens",
    "La vie, c'est essayer des choses pour voir si elles fonctionnent. -Ray Bradbury",
    "La plupart des échecs de la vie sont des personnes qui n'ont pas réalisé à quel point elles étaient proches du succès lorsqu'elles ont abandonné. -Thomas A. Edison",
    "Gardez le sourire, parce que la vie est une chose magnifique et qu'il y a tellement de raisons de sourire. -MarilynMonroe",
    "La vie est une longue leçon d'humilité. -James M. Barrie",
    "Aimez la vie que vous vivez. Vis la vie que tu aimes. -Bob Marley",
    "La vie est soit une aventure audacieuse, soit rien du tout. -HelenKeller",
    "Vous avez un cerveau dans votre tête. Vous avez des pieds dans vos chaussures. Tu peux te diriger dans la direction que tu veux. -Dr.Seuss",
    "La vie est faite de tant de séparations soudées ensemble. -CharlesDickens",
    "Votre temps est limité, alors ne le gaspillez pas en vivant la vie de quelqu'un d'autre. Ne vous laissez pas piéger par le dogme - qui consiste à vivre avec les résultats de la pensée des autres. -SteveJobs",
    "La vie, c'est essayer des choses pour voir si elles fonctionnent. -RayBradbury",
    "Beaucoup des échecs de la vie sont des personnes qui n'ont pas réalisé à quel point elles étaient proches du succès lorsqu'elles ont abandonné. -ThomasA. Edison",
    "Le succès n'est pas définitif ; l'échec n'est pas fatal : c'est le courage de continuer qui compte. -Winston S. Churchill",
    "Le succès vient généralement à ceux qui sont trop occupés pour le chercher. -Henry David Thoreau",
    "La façon de commencer est d'arrêter de parler et de commencer à faire. -Walt Disney",
    "Si vous regardez vraiment de près, la plupart des succès du jour au lendemain ont pris beaucoup de temps. -Steve Jobs",
    "Le secret de la réussite consiste à faire les choses courantes de manière inhabituelle. -John D. Rockefeller Jr.",
    "Je constate que plus je travaille dur, plus j'ai de la chance. -Thomas Jefferson",
    "Le véritable test n'est pas de savoir si vous évitez cet échec, car vous ne le ferez pas. Il s'agit de savoir si vous le laissez s'endurcir ou vous faire honte en restant inactif, ou si vous en tirez des leçons, si vous choisissez de persévérer. -Barack Obama",
    "Le secret de la réussite consiste à faire les choses courantes de manière inhabituelle. -JohnD. Rockefeller Jr.",
    "Je trouve que plus je travaille dur, plus je semble avoir de la chance. -ThomasJefferson",
    "Le succès n'est pas définitif ; l'échec n'est pas fatal : c'est le courage de continuer qui compte. -WinstonS. Churchill",
    "Ne vous laissez pas distraire par les critiques. Rappelez-vous - le seul goût du succès que certaines personnes obtiennent est de faire une bouchée de vous. -ZigZiglar",
    "Le succès vient généralement à ceux qui sont trop occupés pour le chercher. -HenryDavid Thoreau",
    "Je n'ai jamais rêvé du succès, j'ai travaillé pour l'obtenir. -EsteeLauder",
    "Le succès semble être lié à l'action. Les personnes qui réussissent continuent d'avancer. Ils font des erreurs, mais ils n'abandonnent pas.-Conrad Hilton",
    "Il n'y a pas de secrets pour le succès. C'est le résultat de la préparation, du travail acharné et de l'apprentissage de l'échec.  -Colin Powell",
    "Le véritable test n'est pas de savoir si vous évitez cet échec, car vous ne le ferez pas. Il s'agit de savoir si vous le laissez se durcir ou vous faire honte pour vous pousser à l'inaction, ou si vous en tirez des leçons ; si vous choisissez de persévérer. -Barack Obama",
    "Le véritable test n'est pas de savoir si vous évitez cet échec, car vous ne le ferez pas. Il s'agit de savoir si vous le laissez se durcir ou vous faire honte pour vous pousser à l'inaction, ou si vous en tirez des leçons ; si vous choisissez de persévérer. -Barack Obama",
    "Il vaut mieux échouer dans l'originalité que de réussir dans l'imitation. -HermanMelville",
    "Les gens qui réussissent font ce que les gens qui ne réussissent pas ne veulent pas faire. Ne souhaitez pas que ce soit plus facile ; souhaitez que vous soyez meilleur. -JimRohn",
    "La route du succès et la route de l'échec sont presque exactement les mêmes.-Colin R. Davis",
    "J'ai échoué sur le chemin du succès. -ThomasEdison",
    "Si vous fixez vos objectifs à un niveau ridiculement élevé et que c'est un échec, vous échouerez au-dessus du succès de tous les autres. -JamesCameron",
    "Si vous y regardez de plus près, la plupart des réussites du jour au lendemain ont pris beaucoup de temps. -Steve Jobs",
    "Un homme qui réussit est celui qui peut poser des fondations solides avec les briques que les autres ont jetées sur lui. -DavidBrinkley",
    "Les choses marchent mieux pour ceux qui font le meilleur de la façon dont les choses marchent. -JohnWooden",
    "Essayez de ne pas devenir un homme de succès. Devenez plutôt un homme de valeur. -AlbertEinstein",
    "N'ayez pas peur d'abandonner le bon pour aller vers le grand. -JohnD. Rockefeller",
    "Gardez toujours à l'esprit que votre propre résolution à réussir est plus importante que toute autre chose. -AbrahamLincoln",
    "Le succès consiste à marcher d'échec en échec sans perdre son enthousiasme. -WinstonChurchill",
    "Vous savez que vous êtes sur la voie du succès si vous êtes prêt à faire votre travail sans être payé pour cela. -OprahWinfrey",
    "Si vous voulez atteindre l'excellence, vous pouvez y arriver aujourd'hui. Dès cette seconde, cessez de faire un travail moins qu'excellent.  -ThomasJ. Watson",
    "Si vous voulez sincèrement quelque chose, ne l'attendez pas - apprenez à être impatient. -GurbakshChahal",
    "Le seul endroit où le succès passe avant le travail, c'est dans le dictionnaire. -VidalSassoon",
    "Si vous n'êtes pas prêt à risquer l'habituel, vous devrez vous contenter de l'ordinaire. -JimRohn",
    "Avant toute chose, la préparation est la clé du succès. -AlexanderGraham Bell",
    "Les gens qui réussissent ont un élan. Plus ils réussissent, plus ils veulent réussir et plus ils trouvent un moyen de réussir. De même, lorsque quelqu'un échoue, la tendance est de s'engager dans une spirale descendante qui peut même devenir une prophétie auto-réalisatrice. -TonyRobbins",
    "Vous ratez 100% des tirs que vous ne prenez pas. -Wayne Gretzky",
    "Que tu penses que tu peux ou que tu penses que tu ne peux pas, tu as raison. -Henry Ford",
    "J'ai appris au fil des ans que lorsque l'on a une idée bien arrêtée, la peur diminue. -Rosa Parks",
    "Je ne peux pas changer le monde à moi seul, mais je peux jeter une pierre sur l'eau pour créer de nombreuses ondulations. -Mère Teresa",
    "Rien n'est impossible, le mot lui-même dit : \"Je suis possible\". -Audrey Hepburn",
    "La question n'est pas de savoir qui va me laisser faire, mais qui va m'en empêcher. -Ayn Rand",
    "La seule personne que vous êtes destiné à devenir est celle que vous décidez d'être. -Ralph Waldo Emerson",
    "Croyez que vous pouvez et vous êtes à mi-chemin. -ThéodoreRoosevelt",
    "La seule personne que vous êtes destiné à devenir est la personne que vous décidez d'être. -RalphWaldo Emerson",
    "J'ai appris que les gens oublieront ce que vous avez dit, les gens oublieront ce que vous avez fait, mais les gens n'oublieront jamais ce que vous leur avez fait ressentir. -MayaAngelou",
    "La question n'est pas de savoir qui va me laisser faire ; c'est de savoir qui va m'arrêter. -AynRand",
    "Gagner n'est pas tout, mais vouloir gagner l'est. -VinceLombardi",
    "Que tu penses que tu peux ou que tu penses que tu ne peux pas, tu as raison. -HenryFord",
    "Vous devenez ce que vous croyez. -OprahWinfrey",
    "La chose la plus difficile est la décision d'agir, le reste n'est que ténacité. -AmeliaEarhart",
    "Comme c'est merveilleux que personne n'ait à attendre un seul instant avant de commencer à améliorer le monde. -AnneFrank",
    "Une vie non examinée ne vaut pas la peine d'être vécue. -Socrates",
    "Tout ce que vous avez toujours voulu se trouve de l'autre côté de la peur. -GeorgeAddair",
    "Rêvez grand et osez échouer. -NormanVaughan",
    "Vous pouvez être déçu si vous échouez, mais vous êtes condamné si vous n'essayez pas.-Beverly Sills",
    "La vie, c'est 10% de ce qui m'arrive et 90% de la façon dont j'y réagis. -CharlesSwindoll",
    "Peu importe la vitesse à laquelle vous avancez, tant que vous ne vous arrêtez pas.-Confucius",
    "Quand tout semble aller contre vous, rappelez-vous que l'avion décolle contre le vent, pas avec. -HenryFord",
    "Trop d'entre nous ne vivent pas leurs rêves parce qu'ils vivent leurs peurs. -LesBrown",
    "J'ai appris au fil des ans que lorsque l'on a une idée bien arrêtée, cela diminue la peur. -RosaParks",
    "Je n'ai pas raté le test. J'ai juste trouvé 100 façons de le faire mal. -Benjamin Franklin",
    "Si on vous offre un siège sur une fusée, ne demandez pas quel siège ! Montez simplement dessus.  -SherylSandberg",
    "J'attribue mon succès à cela : Je n'ai jamais donné ou accepté d'excuse. -FlorenceNightingale",
    "e préfère mourir de passion que d'ennui. -Vincentvan Gogh",
    "Si tu regardes ce que tu as dans la vie, tu auras toujours plus. Si vous regardez ce que vous n'avez pas dans la vie, vous n'en aurez jamais assez. -OprahWinfrey",
    "Rêver, après tout, est une forme de planification. -GloriaSteinem",
    "Tout ce que l'esprit de l'homme peut concevoir et croire, il peut le réaliser. -NapoléonHill",
    "Premièrement, ayez un idéal pratique défini et clair ; un but, un objectif. Deuxièmement, ayez les moyens nécessaires pour atteindre vos fins ; la sagesse, l'argent, les matériaux et les méthodes. Troisièmement, adaptez tous vos moyens à cette fin. -Aristote",
    "La vie est un mystère qu'il faut vivre, et non un problème à résoudre. - Gandhi",
    "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte. - Winston Churchill",
    "Le bonheur n'est pas quelque chose de prêt à l'emploi. Il vient de vos propres actions. - Dalai Lama",
    "La plus grande gloire de la vie ne réside pas dans la chute, mais dans le fait de se relever chaque fois que l'on tombe. -Nelson Mandela",
    "Dans vingt ans, vous serez plus déçu par les choses que vous n'avez pas faites que par celles que vous avez faites. Alors, larguez les amarres, éloignez-vous du port sûr, attrapez les alizés dans vos voiles. Explorez, rêvez, découvrez. -MarkTwain",
];
